export const ADD_POST = 'POST_ACTION:ADD_POST';
export const SET_ALL_POSTS = 'POST_ACTION:SET_ALL_POSTS';
export const LOAD_MORE_POSTS = 'POST_ACTION:LOAD_MORE_POSTS';
export const TOGGLE_LIKE = 'POST_ACTION:TOGGLE_LIKE';
export const SET_EXPANDED_POST = 'POST_ACTION:SET_EXPANDED_POST';
export const SET_UPDATED_POST = 'POST_ACTION:SET_UPDATED_POST';
export const ADD_COMMENT = 'POST_ACTION:ADD_COMMENT';
export const SET_ALL_REACTIONS = 'POST_ACTION:SET_ALL_REACTIONS';
export const SET_DELETED_POST = 'POST_ACTION:SET_DELETED_POST';

