export const SET_USER = 'PROFILE_ACTION:SET_USER';
export const SET_USER_FORM_UPDATE = 'PROFILE_ACTION:SET_USER_FORM_UPDATE';
export const SET_AVATAR_CHANGE = 'PROFILE_ACTION:SET_AVATAR_CHANGE';
export const SET_AVATAR_DELETE = 'PROFILE_ACTION:SET_AVATAR_DELETE';
